// frontend/src/components/FormButtons.vue
<template>
  <div class="form-action-buttons">
    <v-btn type="submit" :text="t('forms.save')" color="primary" @click.prevent="save" :loading="isSaving" />
    <v-btn :text="t('forms.cancel')" @click="cancel" />
  </div>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

defineProps<{
  isSaving?: boolean
}>()

const emit = defineEmits(['save', 'cancel'])

function save() {
  emit('save')
}

function cancel() {
  emit('cancel')
}
</script>

<style scoped lang="scss">
.form-action-buttons {
  margin-top: 10px;
  display: flex;
  gap: 10px;
}
</style>

// frontend-react/src/components/FormButtons.tsx
import { ReactNode } from 'react'
import { Button } from '@heroui/react'
import { useTranslation } from 'react-i18next'

export interface FormButtonsProps {
  onCancel: () => void;
  isSaving: boolean
}

export function FormButtons(props: FormButtonsProps): ReactNode {
  const { t } = useTranslation()
  const { onCancel, isSaving } = props
  return (
    <div className="flex gap-3">
      <Button color="primary" type="submit" isLoading={isSaving}>{t('forms.save')}</Button>
      <Button color="default" onPress={onCancel} isDisabled={isSaving}>
        {t('forms.cancel')}
      </Button>
    </div>
  )
}
